apiVersion: v1
kind: Service
metadata:
  name: {{ include "entrypoint.fullname" . }}
  labels:
    {{- include "entrypoint.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: entrypoint
