apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-manager
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "pods/log" ]
    verbs: [ "create", "delete", "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "create", "delete" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manage-pods-across-namespaces
subjects:
  - kind: ServiceAccount
    name: pod-manager
    namespace: apps
roleRef:
  kind: ClusterRole
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io
