name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Task
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
      - name: Build ${{ matrix.app }}
        run: task apps/docker/build APP=${{ matrix.app }} TAG=latest
      - name: Push ${{ matrix.app }}
        run: task apps/docker/push APP=${{ matrix.app }} TAG=latest
    strategy:
      matrix:
        app: [ entrypoint ]